#!/bin/bash

usage() {
        echo "Usage: $0 [-p]" /path/to/your/android-ndk 1>&2
        exit 1
}

while getopts :ph OPT
do
    case $OPT in
        p)  ENABLE_PIE=1
            ;;
        h)  usage
            ;;
    esac
done

shift $((OPTIND - 1))

export TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
$1/build/tools/make-standalone-toolchain.sh \
    --toolchain=arm-linux-androideabi-4.9 \
    --arch=arm \
    --install-dir=$TOOLCHAIN \
    --platform=android-9
export PATH=$TOOLCHAIN/bin:$PATH
export AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar
export CC=$TOOLCHAIN/bin/arm-linux-androideabi-gcc
export CXX=$TOOLCHAIN/bin/arm-linux-androideabi-g++
export LINK=$TOOLCHAIN/bin/arm-linux-androideabi-g++


if [ "$ENABLE_PIE" ]; then
    ./configure \
	--pie \
	--dest-cpu=arm \
	--dest-os=android
else
    ./configure \
	--dest-cpu=arm \
	--dest-os=android
fi
